server:
  port: 8080

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      routes:

        - id: service-1
          uri: lb://service-1
          predicates:
          - Path=/service1

        - id: service-2
          uri: lb://service-2
          predicates:
          - Path=/service2

        - id: ws-app
          uri: lb://ws-service
          predicates:
          - Host=example.com:8080
          filters:
          - PreserveHostHeader

        - id: ws
          uri: lb:ws://ws-service
          predicates:
          - Host=example.com:8080
          filters:
          - PreserveHostHeader
